### ISSUE TITLE
Can't download data from Aws

### ISSUE THREAD

**Issue by mingnet** [geotrellis/geotrellis-transit#79]
I want to run and test geotrellis-transit. But It has occurs some errors like below: 

```
make fetch

mkdir -p graph
aws s3 cp s3://geotrellis-transit/transit.edges graph/
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

It can't download data from Aws. I had tested my count and It allowed access my own file.

**Comment by asaf-erlich** [comment]
I'm having the same problem. I assume the s3 bucket and key combination is not set to be public readable? Is it intended to be? It would be nice if it were.

**Comment by rossbernet** [comment]
Just set it to public read. Let me know if this remains an issue.
